---
- hosts: nodeip
  tasks:
  - name: Create User
    user:
      name: hemantpatil1
      state: present
      uid: 6666
  - name: Create file
    file:
      name: /home/ubuntu/myfile
      state: touch
